[project]
name = "10-website-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.116.0",
    "beautifulsoup4>=4.14.3",
    "flask>=3.1.2",
    "google-genai>=2.10.0",
    "playwright>=1.57.0",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
]
